FROM tflite-export
RUN apt-get update && apt-get install -y --no-install-recommends libxcb-shm0 libxcb1 libxcb-xkb1 libxkbcommon0 libglib2.0-0 libsm6 libxext6 libxrender-dev libgomp1 && rm -rf /var/lib/apt/lists/*
