FROM tflite-export
COPY noob/opencv_python_headless-5.0.0.93-cp37-abi3-manylinux_2_28_x86_64.whl /tmp/
COPY noob/ultralytics-8.3.253-py3-none-any.whl /tmp/
COPY noob/tensorflow-2.21.0-cp311-cp311-manylinux_2_27_x86_64.whl /tmp/
RUN pip install --no-index --no-deps /tmp/opencv_python_headless-5.0.0.93-cp37-abi3-manylinux_2_28_x86_64.whl && \
    pip install --no-index --no-deps /tmp/ultralytics-8.3.253-py3-none-any.whl --force-reinstall && \
    pip install --no-deps /tmp/tensorflow-2.21.0-cp311-cp311-manylinux_2_27_x86_64.whl --force-reinstall && \
    rm /tmp/*.whl
